version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":robot: ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":robot: build(deps)"
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      exclude:
        - "*" # No publication date was available from the registry.
    commit-message:
      prefix: ":robot: build(deps)"
    groups:
      docker:
        patterns:
          - "*"
