version: 2

builds:
  - main: ./cmd/versi
    binary: versi
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=1
    tags:
      - odbc

    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
          # unixODBC - downloaded.
          - CGO_LDFLAGS=-L/usr/lib/aarch64-linux-gnu -lodbc

      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
          # Minimum supported macOS version in unixODBC.
          - MACOSX_DEPLOYMENT_TARGET=13.0
          # unixODBC - cross-compiled.
          - CGO_CFLAGS=-I/opt/unixodbc-arm64/include
          - CGO_LDFLAGS=-L/opt/unixodbc-arm64/lib -lodbc -liconv

      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
          # Minimum supported macOS version in unixODBC.
          - MACOSX_DEPLOYMENT_TARGET=13.0
          # unixODBC - cross-compiled.
          - CGO_CFLAGS=-I/opt/unixodbc-amd64/include
          - CGO_LDFLAGS=-L/opt/unixodbc-amd64/lib -lodbc -liconv

      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
          # unixODBC - not required (MinGW handles ODBC natively).
          - CGO_LDFLAGS=-lodbc32

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - NOTICE
      - README.md
      - config/**/*
      - docs/**/*

checksum:
  name_template: "{{.ProjectName}}_v{{.Version}}_checksums.txt"
