# syntax=docker/dockerfile:1

FROM gcr.io/distroless/cc-debian13:nonroot

ARG TARGETARCH

USER nonroot:nonroot

WORKDIR /app
COPY --chmod=700 --chown=nonroot:nonroot dist/versipellis_linux_${TARGETARCH}_*/versi ./
VOLUME ["/app/config", "/app/data"]
ENTRYPOINT ["./versi"]

EXPOSE 4884/tcp 4885/tcp 3885/udp
